# Generated by Django 4.1.5 on 2023-01-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
