# Generated by Django 4.1.5 on 2023-01-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_birth_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
