# Generated by Django 4.1.5 on 2023-01-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Send'), ('2', 'Reject'), ('3', 'Call later'), ('4', 'Successful')], default='1', max_length=20),
        ),
    ]
