# Generated by Django 4.1.5 on 2023-01-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SEND', 'SEND'), ('REJECT', 'REJECT'), ('LATER', 'LATER'), ('SUCCESS', 'SUCCESS')], default='1', max_length=20),
        ),
    ]
