# Generated by Django 4.1.5 on 2023-01-17 05:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=core.models.upload_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SEND', 'SEND'), ('REJECT', 'REJECT'), ('LATER', 'LATER'), ('SUCCESS', 'SUCCESS')], default='SEND', max_length=20),
        ),
    ]
