# Generated by Django 4.1.5 on 2023-01-17 12:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default-article.png', null=True, upload_to=core.models.upload_path_article),
        ),
    ]
